name: Build, Test, and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'openjdk'
          java-version: '22'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Latest Gradle Version
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip
          sudo unzip -d /opt/gradle gradle-8.2.1-bin.zip
          echo "export PATH=$PATH:/opt/gradle/gradle-8.2.1/bin" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Build with Gradle ShadowJar Plugin
        run: gradle shadowJar

      - name: Run tests
        run: gradle test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: media-roulette
          path: app/build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: media-roulette

      - name: Save release artifact
        run: |
          mkdir -p release
          cp app/build/libs/*.jar release/

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: media-roulette-release
          path: release/*