name: Build, Test, and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Latest Gradle Version
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip
          sudo unzip -d /opt/gradle gradle-8.2.1-bin.zip
          echo "export PATH=$PATH:/opt/gradle/gradle-8.2.1/bin" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Build with Gradle ShadowJar Plugin
        run: gradle shadowJar

      - name: Run tests
        run: gradle test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: media-roulette
          path: app/build/libs/*.jar

  release:
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
