name: Build, Test, and Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
          
      - name: Build with Gradle ShadowJar Plugin
        run: ./gradlew shadowJar
        
      - name: Run tests
        run: ./gradlew test
        
      - name: List build outputs (debug)
        run: |
          echo "Looking for JAR files..."
          find . -name "*.jar" -type f
          echo "Build directory contents:"
          ls -la */build/libs/ 2>/dev/null || echo "No build/libs directories found"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: media-roulette-${{ github.sha }}
          path: |
            build/libs/*.jar
            */build/libs/*.jar
          if-no-files-found: error
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: media-roulette-${{ github.sha }}
          path: artifacts/
          
      - name: Prepare release
        run: |
          mkdir -p release
          find artifacts/ -name "*.jar" -exec cp {} release/ \;
          
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: media-roulette-release-${{ github.sha }}
          path: release/*
          retention-days: 90
